server:
  port: 9528

spring:
  application:
    name: cloudalibaba-sentinel-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: pay_routh1
#          uri: lb://nacos-payment-provider
          uri: http://localhost:9001
          predicates:
            - Path=/pay/**