server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-agent-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1  # 建议使用服务名
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service # lb:RouterBalance
          predicates:
            - Path=/pay/gateway/get/**
            - After=2024-04-04T09:24:21.135007400+08:00[Asia/Shanghai]
#            - Cookie=username,wusw
#            - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性且值为整数的正则表达式
#            - Host=**.wushiwei.com # 请求头要有Host属性且值为以.wushiwei.com结尾的域名
#            - Query=username, \d+
#            - RemoteAddr=192.168.134.1/24
#            - Method=GET,POST
#            - My=diamond
#            - name: My
#              args:
#                userType: diamond
        - id: pay_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/getInfo/**

        - id: pay_routh3
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/**
#            - Path=/gateway/filter/** # 配合下面的PrefixPath
#            - Path=/xyz/abc/{segment} # 配合下面的SetPath测试，{segment}的内容会被SetPath取代
          filters:
            - My=wusw
#            - RedirectTo=302, http://www.baidu.com/ # The status parameter should be a 300 series redirect HTTP code, such as 301
#            - PrefixPath=/pay # 隐藏前缀，保护地址
#            - SetPath=/pay/gateway/{segment} # {segment}表示占位符，可以写任意值(abc)但上下要一致
#            - AddRequestHeader=X-Request-Wusw1,wuswValue1
#            - AddRequestHeader=X-Request-Wusw2,wuswValue2
#            # 移除前：请求头: sec-fetch-site, 请求值: none
#            - RemoveRequestHeader=sec-fetch-site
#            # 更新前：请求头: sec-fetch-mode, 请求值: navigate
#            - SetRequestHeader=sec-fetch-mode,Blue-update-by-wusw
#            - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k，v
#            - RemoveRequestParameter=customerName # 删除url请求参数customerName，即使你传递过，来也是null
#            - AddResponseHeader=X-Response-wusw,BlueResponse
#            - SetResponseHeader=Date,2099-11-11
#            - RemoveResponseHeader=Content-Type # 出现中文乱码

